global:
  scrape_interval:     10s
  evaluation_interval: 10s # rule evaluation

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090', 'localhost:9100', 'localhost:8000']
